/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-07-21 13:38:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;

public final class buyer_005fsignin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1620811467066L));
    _jspx_dependants.put("/head.jsp", Long.valueOf(1624881837646L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1625620119681L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"static/css/form.css\" />\r\n");
      out.write("     <script src=\"https://www.google.com/recaptcha/api.js\" async defer></script>\r\n");
      out.write("    ");
      out.write("     <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("     <link rel=\"icon\"  href=\"static/images/favicon.png\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"static/css/font-awesome.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"static/css/bootstrap.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"static/css/common.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"static/css/color.css\" />\r\n");
      out.write("    <style>\r\n");
      out.write("  \r\n");
      out.write("\t.autocom-box{\r\n");
      out.write("\t  position:absolute;\r\n");
      out.write("\t  z-index : 9999;\r\n");
      out.write("\t  border-top: 1px solid black;\r\n");
      out.write("\t  box-shadow:4px 4px 8px -1px black;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.navbar-search{\r\n");
      out.write("\t  position :relative;\r\n");
      out.write("\t  padding : 0px 15px;\r\n");
      out.write("\t  \r\n");
      out.write("\t}\r\n");
      out.write("\t#myframe{\r\n");
      out.write("\tbackground-color : white;\r\n");
      out.write("\t position:absolute;\r\n");
      out.write("\t  z-index : 9999;\r\n");
      out.write("\t  border-top: 1px solid black;\r\n");
      out.write("\t  box-shadow:4px 4px 8px -1px black;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\" integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js\" integrity=\"sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("    <title>Annapurna   :   Sign In as Seller </title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div class=\"row fixed-top white border-light border \" id=\"row-a\">\r\n");
      out.write("            <div class=\"col-3 border border-light\" id=\"col-a\">\r\n");
      out.write("                <img src=\"static/images/home.png\" class=\"mr-4 pb-1\" id=\"img-a1\">\r\n");
      out.write("                <a href=\"index.jsp\" class=\"text-primary\">Home</a>\r\n");
      out.write("                <img src=\"static/images/a2.png\" class=\"\" id=\"img-a2\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("   \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid\" id=\"con-header\">\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("        <div class=\"row fixed-top\" id=\"row-b\">\r\n");
      out.write("            <div class=\"col\" id=\"col-b\">\r\n");
      out.write("                     <div class=\"navbar navbar-expand-lg black\" id=\"navi\">\r\n");
      out.write("                        <a class=\"ann\" href=\"\"><img src=\"static/images/a7.png\" id=\"ann\"></a>\r\n");
      out.write("                        <ul class=\"navbar-nav black justify-content-center\">\r\n");
      out.write("                            <li class=\"nav-item dropdown\">\r\n");
      out.write("                                \r\n");
      out.write("                                <form class=\"form-inline ml-5\"  >\r\n");
      out.write("                                 \r\n");
      out.write("                                  \r\n");
      out.write("                                  ");
 String nm = (String)session.getAttribute("nm");
                                     if(nm !=null){
      out.write("\r\n");
      out.write("                                    <button class=\"btn btn-primary dropdown-toggle btn-sm my-2\" data-toggle=\"dropdown\" id=\"sel\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</button>\r\n");
      out.write("                                    ");
}else{ 
      out.write("\r\n");
      out.write("                                    <button class=\"btn btn-primary dropdown-toggle btn-sm my-2\" data-toggle=\"dropdown\" id=\"sel\">All</button>\r\n");
      out.write("                                    ");
} 
      out.write("\r\n");
      out.write("                                     <div class=\"dropdown-menu\" id=\"id_menu\">\r\n");
      out.write("                                          <li class=\"dropdown-item nav-link  inu\" id=\"all\" >All</li>\r\n");
      out.write("                                          <li  class=\"dropdown-item nav-link inu\"  id=\"all_shops\">Shops</li>\r\n");
      out.write("                                           <li class=\"dropdown-item nav-link inu\" id=\"all_products\">Products</li>\r\n");
      out.write("                                    \r\n");
      out.write("                                    </div> \r\n");
      out.write("                                  \r\n");
      out.write("                                <!-- <select class=\"btn btn-primary btn-sm p-0\" style=\"width:70px\" id=\"sel\">\r\n");
      out.write("                                    <option class=\" text-dark white d-none\" id=\"all\">All</option>\r\n");
      out.write("                                    <option class=\"white text-dark\" id=\"all_products\" style=\"cursor:pointer\">Products</option>\r\n");
      out.write("                                    <option class=\"white text-dark\" id=\"all_shops\">Shops</option>\r\n");
      out.write("                                   </select> -->   \r\n");
      out.write("                                  <div class=\"navbar-search smallsearch px-0  bg-primary border border-primary\"  id=\"body-b\"> \r\n");
      out.write("                                  \r\n");
      out.write("                                  <input type=\"search\" placeholder=\"Search\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${like}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  name = \"searching\" autocomplete=\"off\" class=\"navbar-input btn-sm form-control\" id=\"search\">\r\n");
      out.write("                                  \r\n");
      out.write("                                  <div class=\"autocom-box \" id=\"id_autocom\">\r\n");
      out.write("                                   \r\n");
      out.write("                                    <iframe src=\"2.jsp\" scrolling=\"no\" id=\"myframe\" class=\"\" width=\"500px;\" ></iframe> \r\n");
      out.write("                                   \r\n");
      out.write("                                   \r\n");
      out.write("                                  </div>\r\n");
      out.write("                                 \r\n");
      out.write("                                  </div>\r\n");
      out.write("                                   <input type=\"submit\" value=\"search\" id=\"srh\" class=\"ml-1 btn btn-primary  btn-sm\" >\r\n");
      out.write("                                 </form>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"nav-item dropdown mx-5\"> \r\n");
      out.write("                              \r\n");
      out.write("                                <a href=\"\" class=\" nav-link dropdown-toggle btn btn-secondary mt-2 mx-5 btn-sm\" id=\"jbp\" data-toggle=\"dropdown\">Jabalpur</a>\r\n");
      out.write("                                <div class=\"dropdown-menu\">\r\n");
      out.write("                                    <a href=\"\" class=\"dropdown-item nav-link\">Jabalpur</a>\r\n");
      out.write("                                    <a href=\"\" class=\"dropdown-item nav-link\">Vidisha</a>\r\n");
      out.write("                                    <a href=\"\" class=\"dropdown-item nav-link\">Bhopal</a>\r\n");
      out.write("                                    <a href=\"\" class=\"dropdown-item nav-link\">Indore</a>\r\n");
      out.write("                                    <a href=\"\" class=\"dropdown-item nav-link\">Gwalior</a>\r\n");
      out.write("                                    <a href=\"\" class=\"dropdown-item nav-link\">Amarkanthak</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"nav-item dropdown mr-2 \" id=\"acc-li\">\r\n");
      out.write("                             <a  href=\"\" class=\"btn-sm btn nav-link btn-dark border-light \" data-toggle=\"dropdown\" id=\"account\">Account</a> \r\n");
      out.write("                               <ul>\r\n");
      out.write("                               <div class=\"dropdown-menu bg-dark\">\r\n");
      out.write("                                   \r\n");
      out.write("                                    <a href=\"buyer_signin.jsp\"  class=\"dropdown-item nav-link text-white\"><li class=\"fa fa-sign-in text-primary\"></li>&nbsp; &nbsp; SignIn</a> \r\n");
      out.write("                                           \r\n");
      out.write("                                    <a href=\" \"  class=\"dropdown-item dropdown-toggle nav-link text-white\" data-toggle=\"dropdown\"><li class=\"fa fa-user-plus text-primary \"></li>&nbsp;&nbsp; SignUp</a>\r\n");
      out.write("                                           <ul>\r\n");
      out.write("                                            <div class=\"dropdown-menu bg-info\">\r\n");
      out.write("                                                <a href=\"buyer_signup.do\" class=\"dropdown-item text-white nav-link\"><li class=\"fa fa-shopping-bag text-danger\"></li>&nbsp;&nbsp;SignUp as Buyer</a>\r\n");
      out.write("                                                <a href=\"seller_signup.do \" class=\"dropdown-item text-white nav-link\"><li class=\"fa fa-balance-scale text-danger\"></li>&nbsp;&nbsp;SignUp as Seller</a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            </ul>                    \r\n");
      out.write("                                </div>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li> \r\n");
      out.write("                            <!-- <li class=\"nav-item \" id=\"cart-li\">\r\n");
      out.write("                                 <img src =\"static/images/cart5.png\" class=\"\" id=\"cart\" >\r\n");
      out.write("                            </li>    -->\r\n");
      out.write("                             <a class=\"display-4 \" href=\"#\"><li class=\"fa fa-cart-plus text-primary float-right text-center py-0\"></li> </a>   \r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </div>\r\n");
      out.write("              </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("       \r\n");
      out.write("   <script type=\"text/javascript\" src=\"static/js/common_header.js\"></script>");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"container-fluid\" id=\"con-body\">\r\n");
      out.write("       <div class=\"row mb-5\" id=\"row-c1\">\r\n");
      out.write("           <div class=\"col-4 border  my-5  mx-auto px-3 shadow\">\r\n");
      out.write("               \r\n");
      out.write("             <div class= \"row  text-center  bg-light mb-5 text-white\">\r\n");
      out.write("               <div class=\"col-6 p-0\"><a  href=\"seller_signin.do\" class=\" btn btn-light n btn-block\">SignIn as Seller</a></div>\r\n");
      out.write("               <div class=\"col-5 bg-info p-0\"><a class=\"btn btn-info n  btn-block\">SignIn as Buyer</a></div>\r\n");
      out.write("               <div class=\"col-1 bg-info p-0\"><a href=\"index.jsp\"><h4><li class=\"fa fa-times text-white  text-center p-0\"></li></h4></a>  </div>\r\n");
      out.write("               \r\n");
      out.write("               </div>\r\n");
      out.write("                     \r\n");
      out.write("                <form action=\"#\" method=\"post\" class=\"w-75 \" id=\"form\">\r\n");
      out.write("                    <div class=\"form-group mb-5\">\r\n");
      out.write("                    <label for=\"email\" class=\" text-info \">Email</label>\r\n");
      out.write("                    <input type=\"email\"  name=\"email\" id=\"id_email\" class=\"form-control shadow\" autocomplete = \"off\" >\r\n");
      out.write("                    <small class=\"form-text sl d-none invalid-feedback\">Invalid Email</small>\r\n");
      out.write("                   </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               <div class=\"form-group mb-5\">\r\n");
      out.write("                    <label for=\"id_passw\" class=\"text-info\">Password</label>\r\n");
      out.write("                    <div class=\"input-group\"><input type=\"password\" id=\"id_passw\" name=\"password\" class=\"form-control shadow eye_input\" autocomplete=\"off\" >\r\n");
      out.write("  \r\n");
      out.write("                     <span class=\"  border border-info \" id=\"id_eyebox\" ><i class=\"input-group-addon fa fa-eye fa-spin text-info mt-2 mx-2\" id=\"id_eye\"  area-hidden=\"true\"></i></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <small class=\"form-text sl d-none invalid-feedback\">Invalid Password</small>\r\n");
      out.write("                    <small class=\"form-text text-muted \">Maximum 8 chracters</small>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  \r\n");
      out.write("                    \r\n");
      out.write("                  <div class=\"g-recaptcha ml-4 mb-5 d-inline-block shadow\" data-sitekey=\"6LfDyNwaAAAAAMr1gklZ0xZrIhPlULARiMwGpjYK\"></div>\r\n");
      out.write("                  \t\r\n");
      out.write("                  <div class=\"text-center\"><input type=\"submit\" value=\"Log-In\" class=\" shadow-lg btn px-4 mb-4 btn-primary\" ></div>\r\n");
      out.write("                  <small><a href=\"\"  class=\"mb-5\">Forgot password  ?</a></small>\r\n");
      out.write("                  <h6 class=\"mt-4 mb-3\"><a href=\"\" class=\"dropdown\"  data-toggle=\"dropdown\">Create a new Account</a>\r\n");
      out.write("                  <div class=\"dropdown-menu bg-info\">\r\n");
      out.write("                            <a href=\"buyer_signup.do\" class=\"dropdown-item text-white nav-link\">SignUp as Buyer</a>\r\n");
      out.write("                            <a href=\"seller_signup.do\" class=\"dropdown-item text-white nav-link\">SignUp as Seller</a>\r\n");
      out.write("                     </div> \r\n");
      out.write("                     </h6>\r\n");
      out.write("               </form>\r\n");
      out.write("           </div>\r\n");
      out.write("       </div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("    ");
      out.write("<div class=\"container-fluid bg-dark text-white border border-primary\" id=\"con-footer\">\r\n");
      out.write("       <div class=\"row\" id=\"row-h\">\r\n");
      out.write("           <div class=\"col-4 pl-5\">\r\n");
      out.write("              <h5 class=\"mb-4\"><u>About us</u></h5>\r\n");
      out.write("              <p>\r\n");
      out.write("                <img src=\"static/images/a7.png\" class=\"\" id=\"ann2\">\r\n");
      out.write("                <big>Annapurnaa  </big></br> \r\n");
      out.write("                <small>Online Grocery Shopping Platform</small> \r\n");
      out.write("                <h6> <a href=\"\" >Terms and policies</a></h6>\r\n");
      out.write("                 \r\n");
      out.write("              </p>\r\n");
      out.write("           </div>\r\n");
      out.write("           <div class=\"col-4  pl-5\">\r\n");
      out.write("              <h5 class=\"mb-4\"><u>Contact us</u></h5>\r\n");
      out.write("                 <img src=\"static/images/fb.png\" class=\"h-w3 mr-3 mb-1\" >Palaksahu@facebook.com<br>\r\n");
      out.write("                 <img src=\"static/images/e.png\" class=\"h-w3 mr-3 mb-1\" >sahupalak@gmail.com<br>\r\n");
      out.write("                 <img src=\"static/images/t.png\" class=\"h-w3 mr-3 mb-1\"  >Palak sahu@twitter .com<br>\r\n");
      out.write("                  Phone  -  7828423047,9174623918 \r\n");
      out.write("              </p>\r\n");
      out.write("           </div>\r\n");
      out.write("           <div class=\"col-4 pl-5\">\r\n");
      out.write("              <h5 class=\"mb-3\"><u>Some quick links</u></h5>\r\n");
      out.write("              <p>\r\n");
      out.write("               <a class=\"\">SignIn</a> <br>\r\n");
      out.write("               <a class=\"\">SignUp</a><br>\r\n");
      out.write("               <a class=\"\">All products</a><br>\r\n");
      out.write("               <a class=\"\">All Shops</a><br>\r\n");
      out.write("               <a class=\"\">Back to Top</a>\r\n");
      out.write("              </p>\r\n");
      out.write("           </div>\r\n");
      out.write("\r\n");
      out.write("       </div>\r\n");
      out.write("\r\n");
      out.write(" </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
