/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-07-21 13:39:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import models.ProductPic;
import models.Product;
import java.util.ArrayList;
import models.ShopPic;
import models.Shop;

public final class seller_005fhomePage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1620811467066L));
    _jspx_dependants.put("/head.jsp", Long.valueOf(1624881837646L));
    _jspx_dependants.put("/seller_header.jsp", Long.valueOf(1623915840747L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("models.Shop");
    _jspx_imports_classes.add("models.Product");
    _jspx_imports_classes.add("models.ShopPic");
    _jspx_imports_classes.add("models.ProductPic");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("      ");
      out.write("     <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("     <link rel=\"icon\"  href=\"static/images/favicon.png\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"static/css/font-awesome.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"static/css/bootstrap.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"static/css/common.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"static/css/color.css\" />\r\n");
      out.write("    <style>\r\n");
      out.write("  \r\n");
      out.write("\t.autocom-box{\r\n");
      out.write("\t  position:absolute;\r\n");
      out.write("\t  z-index : 9999;\r\n");
      out.write("\t  border-top: 1px solid black;\r\n");
      out.write("\t  box-shadow:4px 4px 8px -1px black;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.navbar-search{\r\n");
      out.write("\t  position :relative;\r\n");
      out.write("\t  padding : 0px 15px;\r\n");
      out.write("\t  \r\n");
      out.write("\t}\r\n");
      out.write("\t#myframe{\r\n");
      out.write("\tbackground-color : white;\r\n");
      out.write("\t position:absolute;\r\n");
      out.write("\t  z-index : 9999;\r\n");
      out.write("\t  border-top: 1px solid black;\r\n");
      out.write("\t  box-shadow:4px 4px 8px -1px black;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\" integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js\" integrity=\"sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <title>Annapurna   :   My Account </title>\r\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"static/css/dropzone.min.css\" />\r\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"static/css/seller_home.css\" />\r\n");
      out.write("      <style>\r\n");
      out.write("  .card-sm:hover{\r\n");
      out.write("\t     transform: scale(1.2);\r\n");
      out.write("\t     transition: transform 0.3s ease;\r\n");
      out.write("\t    \r\n");
      out.write("\t     cursor : pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t.f{\r\n");
      out.write("\t font-size : 13px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("      <div class=\"row fixed-top white border-light border \" id=\"row-a\">\r\n");
      out.write("            <div class=\"col-3 border border-light\" id=\"col-a\">\r\n");
      out.write("                <img src=\"static/images/home.png\" class=\"mr-4 pb-1\" id=\"img-a1\">\r\n");
      out.write("                <span class=\"text-secondary\"> My Account</span>\r\n");
      out.write("                <img src=\"static/images/a2.png\" class=\"\" id=\"img-a2\">\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("     ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid\" id=\"con-header\">\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"row fixed-top\" id=\"row-b\">\r\n");
      out.write("            <div class=\"col\" id=\"col-b\">\r\n");
      out.write("                     <div class=\"navbar navbar-expand-lg black\" id=\"navi\">\r\n");
      out.write("                        <a class=\"ann\" href=\"\"><img src=\"static/images/a7.png\" id=\"ann\"></a>\r\n");
      out.write("                        <ul class=\"navbar-nav black justify-content-center\">\r\n");
      out.write("                            <li class=\"nav-item dropdown\">\r\n");
      out.write("                                <form class=\"form-inline ml-5\">\r\n");
      out.write("                                    <button class=\"btn btn-primary dropdown-toggle btn-sm my-2\" data-toggle=\"dropdown\">All</button>\r\n");
      out.write("                                    <div class=\"dropdown-menu\">\r\n");
      out.write("                                          <a href=\"#\" class=\"dropdown-item nav-link\">Products</a>\r\n");
      out.write("                                          <a href=\"#\" class=\"dropdown-item nav-link\">Shops</a>\r\n");
      out.write("                                    </div>   \r\n");
      out.write("                                  <input type=\"search\"  class=\"form-control btn-sm\" id=\"search\">\r\n");
      out.write("                                  <input type=\"submit\" value=\"search\" id=\"srh\" class=\"ml-1 btn btn-primary btn-sm\" >\r\n");
      out.write("                                 </form>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"nav-item dropdown mx-5\"> \r\n");
      out.write("                              \r\n");
      out.write("                                <a href=\"\" class=\" nav-link dropdown-toggle btn btn-secondary mt-2 mx-5 btn-sm\" id=\"jbp\" data-toggle=\"dropdown\">Jabalpur</a>\r\n");
      out.write("                                <div class=\"dropdown-menu\">\r\n");
      out.write("                                    <a href=\"\" class=\"dropdown-item nav-link\">Jabalpur</a>\r\n");
      out.write("                                    <a href=\"\" class=\"dropdown-item nav-link\">Vidisha</a>\r\n");
      out.write("                                    <a href=\"\" class=\"dropdown-item nav-link\">Bhopal</a>\r\n");
      out.write("                                    <a href=\"\" class=\"dropdown-item nav-link\">Indore</a>\r\n");
      out.write("                                    <a href=\"\" class=\"dropdown-item nav-link\">Gwalior</a>\r\n");
      out.write("                                    <a href=\"\" class=\"dropdown-item nav-link\">Amarkanthak</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"nav-item dropdown mr-2\" id=\"myacc-li\">\r\n");
      out.write("                              <a  href=\"\" class=\"btn-sm btn nav-link btn-dark border-light \" data-toggle=\"dropdown\" id=\"account\">My&nbspAccount</a>\r\n");
      out.write("                               <div class=\"dropdown-menu bg-dark \">\r\n");
      out.write("                               <ul class=\"p-0\">\r\n");
      out.write("                                    <a href=\"seller_profile.do\"  id=\"pro\" class=\"dropdown-item nav-link text-white\"><li class=\"fa fa-user-circle mx-4\"></li>Profile</a>\r\n");
      out.write("                                    <a href=\"\"  class=\"dropdown-item nav-link text-white\"><li class=\"fa fa-handshake-o mx-4 text-white\"></li>Your Orders</a>\r\n");
      out.write("                                    <a href=\"\"  class=\"dropdown-item nav-link text-white\"><li class=\"fa fa-stack-overflow mx-4\"></li>Stock</a> \r\n");
      out.write("                                    <a href=\"\"  class=\"dropdown-item nav-link text-white\"><li class=\"fa fa-commenting-o mx-4\"></li>Messages</a>       \r\n");
      out.write("                                    <a href=\"\"  class=\"dropdown-item nav-link text-white\"><li class=\"fa fa-envelope-o mx-4\"></li> Email</a>\r\n");
      out.write("                                    <a href=\"\"  class=\"dropdown-item nav-link text-white\"><li class=\"fa fa-vcard-o mx-4\"></li>Check Reciepts</a>   \r\n");
      out.write("                                    <a href=\"\"  class=\"dropdown-item nav-link text-white\"><li class=\"fa fa-spinner mx-4\"></li>Check Status</a> \r\n");
      out.write("                                    <a href=\"seller_logout.do\"  class=\"dropdown-item nav-link text-white\"><li class=\"fa fa-sign-out mx-4\"></li>Log-out</a>\r\n");
      out.write("                                    <a href=\"\"  class=\"dropdown-item nav-link text-white\"><li class=\"fa fa-cog fa-spin mx-4\"></li>Settings</a>                                \r\n");
      out.write("                                </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li> \r\n");
      out.write("                           <!-- <li class=\"nav-item\" id=\"cart-li\">\r\n");
      out.write("                              <a href=\"\" class=\"\"><img src =\"static/images/drop.png\"  class=\"border border-primary bg-light text-light \" id=\"drop\" ></a> \r\n");
      out.write("                            </li> -->\r\n");
      out.write("                             <a class=\"display-4 ml-5\" href=\"#\"><li class=\"fa fa-cart-plus text-primary float-right text-center py-0\"></li> </a>                  \r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </div>\r\n");
      out.write("              </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("   \r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    <div class=\"container-fluid \" id=\"con-body\">\r\n");
      out.write("    <div class=\"row text-white display-4 mx-auto py-1 red mb-3\" id=\"id_texure\" ><span class=\"mx-auto \">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shop.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></div>\r\n");
      out.write("    <div class=\"row white \">\r\n");
      out.write("       <div class=\"col-8  mx-auto text-white text-center \" id=\"f-col\">\r\n");
      out.write("        <img alt=\"\" class=\"shadow-lg\" src =\"seller_showpropic.do?propic=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shop.propic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" width=\"1000px\" height=\"500px\">  \r\n");
      out.write("       \r\n");
      out.write("       </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"row mt-5\">\r\n");
      out.write("          <div class=\"col-12  w-100\">\r\n");
      out.write("              <ul class=\"nav nav-tabs text-center \">\r\n");
      out.write("                <li class=\"nav-item  w-50 \">\r\n");
      out.write("                   <a class=\"nav-link  btn btn-lg  shadow btn-outline-primary active border border-info mr-1\" data-toggle=\"tab\" href=\"#products\" id=\"allproducts\">All Products</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item w-50 \">\r\n");
      out.write("                  <a  class=\"nav-link btn btn-lg shadow btn-outline-primary border border-info ml-1\" data-toggle=\"tab\"  href=\"#pics\" id=\"allpics\" >All Pictures </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("              </ul>\r\n");
      out.write("              <div class=\"tab-content text-center\">\r\n");
      out.write("                 \r\n");
      out.write("                 <div class=\"tab-pane active\" id=\"products\" >\r\n");
      out.write("                  <div class=\"card-columns \">\r\n");
      out.write("\t                  <div class=\"card w-50 mt-5 mb-3\" >\r\n");
      out.write("\t                   <a class=\"btn btn-light shadow-lg nav-link  card-body  btn-block pt-5\" href=\"seller_addproduct.do\" id=\"id_addProduct\">Add product<br><li class=\"fa fa-plus-circle\"></li></a>\r\n");
      out.write("\t                  </div>\r\n");
      out.write("\t                  <!-- start -->  \r\n");
      out.write("\t                ");
  Shop shop =  (Shop)session.getAttribute("shop"); 
	                    Product product1 = (Product)session.getAttribute("product");
	                    if(product1!=null){
	                    	session.removeAttribute("product");
	                    }
                    if(shop != null){
                       ArrayList<Product> productList = Product.getSellerProducts(shop);   
                       
                         int c = 1; 
                       for(Product product : productList){  
      out.write("\r\n");
      out.write("                    \t                 \r\n");
      out.write("                       \r\n");
      out.write("                          <!-- start -->\r\n");
      out.write("                      \r\n");
      out.write("                    <div class=\"card shadow-lg border border-info mt-2\" style=\"max-width:1000px\">\r\n");
      out.write("\t\t            <div class=\"row no-gutters\">\r\n");
      out.write("\t\t\t\t             <div class=\"col-5 \">\r\n");
      out.write("\t\t\t\t                        \r\n");
      out.write("\t\t\t\t                <div class=\"carousel slide \" id=\"c");
      out.print(c );
      out.write("\" data-ride=\"carousel\">\r\n");
      out.write("\t\t\t\t                   \r\n");
      out.write("\t\t\t\t\t                  <ol class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t\t\t                     <li data-target=\"#c");
      out.print(c );
      out.write("\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("\t\t\t\t\t                     <li data-target=\"#c");
      out.print(c );
      out.write("\" data-slide-to=\"1\" ></li>\r\n");
      out.write("\t\t\t\t\t                     <li data-target=\"#c");
      out.print(c );
      out.write("\" data-slide-to=\"2\" ></li>\r\n");
      out.write("\t\t\t\t\t                  </ol>\r\n");
      out.write("\t\t\t\t\t                  <div class=\"carousel-inner\">\r\n");
      out.write("\t\t\t\t\t                     \r\n");
      out.write("\t\t\t\t\t\t                       \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t       ");
   if(product != null){
											        	  
											          ArrayList<String> allPicList = ProductPic.getAllPics(product);
											          int count = 0;
											          for(String picPath : allPicList){ 
											        	  if(count == 0){  
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        \t        \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t         \t<div class=\"carousel-item active\">\r\n");
      out.write("\t\t\t\t\t\t                                     <img class=\"d-block w-100\" alt=\"\" src=\"seller_showproductpic.do?picPath=");
      out.print( picPath );
      out.write("\" width=\"150px\" height=\"200px\">      \r\n");
      out.write("\t\t\t\t\t\t                                </div> \r\n");
      out.write("\t\t\t\t\t\t                                \r\n");
      out.write("\t\t\t\t\t\t                               \r\n");
      out.write("\t\t\t\t\t\t                             ");
  count ++; 
						                                } else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t                            \t  \r\n");
      out.write("\t\t\t\t\t\t                            \t  <div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t\t\t                                     <img class=\"d-block w-100\" alt=\"\" src=\"seller_showproductpic.do?picPath=");
      out.print( picPath );
      out.write("\" width=\"150px\" height=\"200px\">      \r\n");
      out.write("\t\t\t\t\t\t                                  </div>\r\n");
      out.write("\t\t\t\t\t\t                            \t \r\n");
      out.write("\t\t\t\t\t\t                            ");
    count++;
						                             }      
											                
											          }
											        } else{
											        	response.sendRedirect("seller_signin.jsp");
											        }        		  
											    
      out.write("                  \r\n");
      out.write("\t\t\t\t\t                  </div>\r\n");
      out.write("\t\t\t\t\t                  <a class=\"carousel-control-prev\" href=\"#c");
      out.print(c );
      out.write("\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("\t\t\t\t\t                     <span class=\"carousel-control-prev-icon shadow-lg bg-secondary\" area-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t                     <span class=\"sr-only\">Previous</span>\r\n");
      out.write("\t\t\t\t\t                  </a>\r\n");
      out.write("\t\t\t\t\t                  <a class=\"carousel-control-next \" href=\"#c");
      out.print(c );
      out.write("\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("\t\t\t\t                     <span class=\"carousel-control-next-icon shadow-lg bg-secondary\" area-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t                     <span class=\"sr-only\">Next</span>\r\n");
      out.write("\t\t\t\t                  </a>\r\n");
      out.write("\t\t\t\t                </div>\r\n");
      out.write("\t\t\t\t                 \r\n");
      out.write("\t\t\t\t           \t </div><!-- col-6/row/col-5 -->\r\n");
      out.write("\t\t\t\t           \r\n");
      out.write("\t\t\t\t           \t <div class=\"col-7 text-left f\">\r\n");
      out.write("\t\t\t\t                 <div class=\"card-body\" style=\"height:205px ;\" >\r\n");
      out.write("\t\t\t\t\t\t                 <h6 class=\"card-title row ml-1\">");
      out.print( product.getBrand() );
      out.write(' ');
      out.write(' ');
      out.print( product.getProductName() );
      out.write("  </h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t         \r\n");
      out.write("\t\t\t\t\t\t\t\t         <div class=\"card-text row \">\r\n");
      out.write("\t\t\t\t\t\t\t\t           <div class=\"col-5\"> Weight -</div> \r\n");
      out.write("\t\t\t\t\t\t\t\t           <div class=\"col-7\">");
      out.print( product.getWeight() );
      out.write("&nbsp;kg</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t          </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t           <div class=\"card-text row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t           <div class=\"col-5\"> MRP  -</div> \r\n");
      out.write("\t\t\t\t\t\t\t\t           <div class=\"col-7\"> <s>Rs&nbsp; ");
      out.print( product.getMrp() );
      out.write("</s>/- </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t          </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t         \r\n");
      out.write("\t\t\t\t\t\t\t\t          <div class=\"card-text row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t           <div class=\"col-5\"> Price -</div> \r\n");
      out.write("\t\t\t\t\t\t\t\t           <div class=\"col-7\">Rs&nbsp;<h6 class=\"d-inline text-primary\">");
      out.print( product.getPrice() );
      out.write("</h6> /-</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t          </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t         \r\n");
      out.write("\t\t\t\t\t\t\t\t          <div class=\"card-text row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t           <div class=\"col-5\"> Quantity -</div> \r\n");
      out.write("\t\t\t\t\t\t\t\t           <div class=\"col-7\">");
      out.print( product.getQuantity() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t          </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t         \r\n");
      out.write("\t\t\t\t\t\t\t\t          <div class=\"card-text row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t           <div class=\"col-5\">Expiry Date -</div> \r\n");
      out.write("\t\t\t\t\t\t\t\t           <div class=\"col-7\">");
      out.print( product.getExdate() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t          </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t          \r\n");
      out.write("\t\t\t\t\t\t\t\t          <div class=\"card-text row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t           <div class=\"col-5\">Details -</div> \r\n");
      out.write("\t\t\t\t\t\t\t\t           <div class=\"col-7\">");
      out.print( product.getDetails().substring(0,30));
      out.write("<a href=\"\" class=\" ml-1 text-primary\">more</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t          </div>  \r\n");
      out.write("\t\t\t\t\t\t\t\t          \r\n");
      out.write("\t\t\t\t                 </div>\r\n");
      out.write("\t\t\t\t                   \r\n");
      out.write("\t\t\t           \t     </div><!-- col-6/row/col-7 -->\r\n");
      out.write("\t\t\t           \t    \r\n");
      out.write("\t\t           </div><!-- col-6/row -->\r\n");
      out.write("\t\t          <div class=\"row no-gutters border\">\r\n");
      out.write("\t\t           \r\n");
      out.write("\t\t           <div class=\"col-6\"><button type=\"submit\" class=\"btn btn-outline-primary btn-sm p-0 btn-block edit\" value=\"");
      out.print(product.getProductId());
      out.write("\" ><li class=\"fa fa-pencil-square  fa-lg \">&nbsp;Edit</li></button></div>\r\n");
      out.write("\t\t           \t\r\n");
      out.write("\t\t           <div class=\"col-6\"><button type=\"button\" class=\"btn btn-outline-danger btn-sm p-0 btn-block del\"   value=\"");
      out.print(product.getProductId());
      out.write("\"  ><li class=\"fa fa-trash-o fa-lg \">&nbsp;Delete</li></button></div>\r\n");
      out.write("\t\t           </div>\r\n");
      out.write("\t\t       \r\n");
      out.write("\t\t        </div>\r\n");
      out.write("                      \r\n");
      out.write("                      <!-- end -->\r\n");
      out.write("                  \r\n");
      out.write("                       \r\n");
      out.write("                       \r\n");
      out.write("                       \r\n");
      out.write("                    \t      \r\n");
      out.write("                    ");
 c++;
                        
                       } 
                       
                       
                       }else{
                    	   
                    	 request.getRequestDispatcher("seller_signin.jsp").forward(request,response);  
                       } 
      out.write("\r\n");
      out.write("                     \r\n");
      out.write("                      \r\n");
      out.write("                     <!-- end -->\r\n");
      out.write("                  </div>\r\n");
      out.write("                 </div>\r\n");
      out.write("               <div class=\"tab-pane black mb-5 h-100 w-100\" id=\"pics\" >    <iframe src=\"1.jsp\" class=\"w-100\" scrolling=\"no\"  style=\"height : 1500px;border:none\"></iframe></div>\r\n");
      out.write("                          </div>\r\n");
      out.write("         </div>\r\n");
      out.write("     </div>\r\n");
      out.write("   </div>\r\n");
      out.write("  \r\n");
      out.write("      \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("     ");
      out.write("<div class=\"container-fluid bg-dark text-white border border-primary\" id=\"con-footer\">\r\n");
      out.write("       <div class=\"row\" id=\"row-h\">\r\n");
      out.write("           <div class=\"col-4 pl-5\">\r\n");
      out.write("              <h5 class=\"mb-4\"><u>About us</u></h5>\r\n");
      out.write("              <p>\r\n");
      out.write("                <img src=\"static/images/a7.png\" class=\"\" id=\"ann2\">\r\n");
      out.write("                <big>Annapurnaa  </big></br> \r\n");
      out.write("                <small>Online Grocery Shopping Platform</small> \r\n");
      out.write("                <h6> <a href=\"\" >Terms and policies</a></h6>\r\n");
      out.write("                 \r\n");
      out.write("              </p>\r\n");
      out.write("           </div>\r\n");
      out.write("           <div class=\"col-4  pl-5\">\r\n");
      out.write("              <h5 class=\"mb-4\"><u>Contact us</u></h5>\r\n");
      out.write("                 <img src=\"static/images/fb.png\" class=\"h-w3 mr-3 mb-1\" >Palaksahu@facebook.com<br>\r\n");
      out.write("                 <img src=\"static/images/e.png\" class=\"h-w3 mr-3 mb-1\" >sahupalak@gmail.com<br>\r\n");
      out.write("                 <img src=\"static/images/t.png\" class=\"h-w3 mr-3 mb-1\"  >Palak sahu@twitter .com<br>\r\n");
      out.write("                  Phone  -  7828423047,9174623918 \r\n");
      out.write("              </p>\r\n");
      out.write("           </div>\r\n");
      out.write("           <div class=\"col-4 pl-5\">\r\n");
      out.write("              <h5 class=\"mb-3\"><u>Some quick links</u></h5>\r\n");
      out.write("              <p>\r\n");
      out.write("               <a class=\"\">SignIn</a> <br>\r\n");
      out.write("               <a class=\"\">SignUp</a><br>\r\n");
      out.write("               <a class=\"\">All products</a><br>\r\n");
      out.write("               <a class=\"\">All Shops</a><br>\r\n");
      out.write("               <a class=\"\">Back to Top</a>\r\n");
      out.write("              </p>\r\n");
      out.write("           </div>\r\n");
      out.write("\r\n");
      out.write("       </div>\r\n");
      out.write("\r\n");
      out.write("     <script type=\"text/javascript\" src=\"static/js/seller_homePage.js\"></script> \r\n");
      out.write("     <script type=\"text/javascript\" src=\"static/js/dropzone.min.js\"></script>\r\n");
      out.write("     \r\n");
      out.write("             \r\n");
      out.write("\t\t    \r\n");
      out.write("   \r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
