package utils;

public class ActivationMessage  {
     public static String getActivationMessage(String name,String email,long activationCode) {
    	
    	 return "<!DOCTYPE html>\r\n"
    	 		+ "<html lang=\"en\">\r\n"
    	 		+ "<head>\r\n"
    	 		+ "    <meta charset=\"UTF-8\">\r\n"
    	 		+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n"
    	 		+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0 , shrink-to-fit=no\">\r\n"
    	 		+ "    <title>Document</title>\r\n"
    	 		+ "      <style>\r\n"
    	 		+ "       #table{\r\n"
    	 		+ "        border : 1px solid blue;\r\n"
    	 		+ "        color:#444444;\r\n"
    	 		+ "        box-shadow : 30px 30px 30px 30px #f2f2f2;\r\n"
    	 		+ "        }\r\n"
    	 		+ "        .bor{\r\n"
    	 		+ "          padding : 3px;\r\n"
    	 		+ "         }\r\n"
    	 		+ "        \r\n"
    	 		+ "        #ann{\r\n"
    	 		+ "        color:white;\r\n"
    	 		+ "        }\r\n"
    	 		+ "        #tr1{\r\n"
    	 		+ "        background-color: black;\r\n"
    	 		+ "        }\r\n"
    	 		+ "        #thank{\r\n"
    	 		+ "          font-size : 60px ;\r\n"
    	 		+ "          font-family: Brush Script MT;\r\n"
    	 		+ "          color : blue;\r\n"
    	 		+ "        }\r\n"
    	 		+ "        .mar{\r\n"
    	 		+ "          margin-left :  150px;\r\n"
    	 		+ "        }\r\n"
    	 		+ "      </style>\r\n"
    	 		+ "    </head>\r\n"
    	 		+ "    <body>\r\n"
    	 		+ "      <table id=\"table\" align=\"center\" width=\"50%\" >\r\n"
    	 		+ "        <tr id=\"tr1\">\r\n"          
    	 		+ "            <th  width=\"100%\" id=\"ann\"><h1>Annapurna</h1></th>\r\n"
    	 		+ "        </tr>\r\n"
    	 		+ "        <tr><td class=\"bor\" colspan=\"2\">Hii,the owner of "+name+"</td></tr>\r\n"
    	 		+ "        <tr><td class=\"bor\" colspan=\"2\" id=\"thank\" align=\"center\">Thanks For Sign-Up</td></tr>\r\n"
    	 		+ "        <tr><th class=\"bor \" colspan=\"2\">Your Login Details are as follows:-</th></tr>\r\n"
    	 		+ "        <tr><td class=\"bor\" colspan=\"2\"><li class=\"mar\">Shop Name:-  "+name+"</li></td></tr>\r\n"
    	 		+ "        <tr><td class=\"bor\" colspan=\"2\"><li class=\"mar\">Email:-  <a href='as.d'>"+email+"</a></li></td></tr>\r\n"
    	 		+ "        \r\n"
    	 		+ "       <tr>\r\n"
    	 		+ "       <th class=\"bor\" colspan=\"2\"><h3><li>Click on the Link Given Below to Activate your Account</li></h3></th>\r\n"
    	 		+ "       </tr>\r\n"
    	 		+ "       <tr><td class=\"bor\" colspan=\"2\"><h2 class=\"mar\"><a href=\"http://localhost:8080/annapurna/activation.do?email="+email+"&activation_code="+activationCode+"\">Link</a></h2></td></tr>\r\n"
    	 		+ "        \r\n"
    	 		+ "        \r\n"
    	 		+ "       \r\n"
    	 		+ "        \r\n"
    	 		+ "      </table>\r\n"
    	 		+ "    </body>\r\n"
    	 		+ "  </html>";
    			 }
}
